name: Create Pull Request from stoplightio/elements

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight UTC on the 1st day of each month
  workflow_dispatch:
    # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full clone to include history

      - name: Setup Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Fetch from upstream
        run: |
          # Create new branch
          git checkout -b update-from-stoplightio-elements

          # Add the upstream repo as a remote
          git remote add upstream https://github.com/stoplightio/elements.git

          # Fetch from upstream
          git fetch upstream main

          # Create a list of commits we're getting for the PR description
          git log HEAD..upstream/main --oneline > commit_list.txt
          
          # Check if there are new commits to pull
          if [ -s commit_list.txt ]; then
            echo "New commits found, will create PR"
            cat commit_list.txt
            COMMIT_SUMMARY=$(cat commit_list.txt)
            echo "COMMIT_SUMMARY<<EOF" >> $GITHUB_ENV
            echo "$COMMIT_SUMMARY" >> $GITHUB_ENV
            echo "EOF" >> $GITHUB_ENV
          else
            echo "No new commits found, exiting workflow"
            exit 78
          fi
          
          # Pull changes from upstream (this preserves commit history)
          git pull upstream main --no-rebase

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ github.token }}
          commit-message: Update from stoplightio/elements
          title: Update from stoplightio/elements
          body: |
            This is an automated pull request to keep in sync with stoplightio/elements repository.
            
            ## Recent Commits From Source Repository
            ```
            ${{ env.COMMIT_SUMMARY }}
            ```
            
            Updates made on: ${{ github.event.repository.updated_at }}
          branch: update-from-stoplightio-elements
          delete-branch: true
