name: Create Pull Request from stoplightio/elements

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at midnight UTC on the 1st day of each month
  workflow_dispatch:
    # Allows manual triggering

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Target Repo
        uses: actions/checkout@v4

      - name: Checkout Source Repo
        uses: actions/checkout@v4
        with:
          repository: stoplightio/elements
          path: source-repo

      - name: Copy Relevant Files
        run: |
          # Create a temporary directory for the files
          mkdir -p ./updated-files

          # Check what files have changed in the source repo compared to your repo
          # This example assumes you're interested in the entire elements package

          # First, copy the specific directories you're interested in
          cp -r source-repo/packages/elements/* ./updated-files/

          # Now use git diff to find and only keep files that are different
          cd ./updated-files

          # List all files in updated-files directory
          find . -type f | while read file; do
            # Remove leading ./ from filename for comparison
            relative_path=${file:2}
            # Check if file exists in target repo
            if [ -f "../$relative_path" ]; then
              # Compare with file in target repo
              if cmp -s "$file" "../$relative_path"; then
                # Files are identical, remove from updated-files
                rm "$file"
              fi
            fi
          done

          # Remove empty directories
          find . -type d -empty -delete

          cd ..

          # Check if there are any changes
          if [ -z "$(ls -A ./updated-files)" ]; then
            echo "No changes detected, exiting workflow"
            exit 78  # neutral exit code, workflow will show as skipped
          fi
      - name: Prepare Files for Pull Request
        run: |
          # Move files from updated-files to the main repo structure
          find ./updated-files -type f | while read file; do
          relative_path=${file#./updated-files/}
          mkdir -p "$(dirname "$relative_path")"
          cp -f "$file" "$relative_path"
          done
    
          # Stage the changes for the PR
          git add .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ github.token }}
          commit-message: Update from stoplightio/elements
          title: Update from stoplightio/elements
          body: |
            This is an automated pull request to keep in sync with stoplightio/elements repository.
            
            Updates made on: ${{ github.event.repository.updated_at }}
          branch: update-from-stoplightio-elements
          delete-branch: true
