name: Create Pull Request from stoplightio/elements

on:
  schedule:
    - cron: '25 16 30 6 *'  # Runs at 16:25 UTC on June 30

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Target Repo
      uses: actions/checkout@v3

    - name: Checkout Source Repo
      uses: actions/checkout@v3
      with:
        repository: stoplightio/elements
        path: source-repo

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        source-directory: source-repo
        commit-message: Update from stoplightio/elements
        title: Update from stoplightio/elements
        body: This is an automated pull request to update from the stoplightio/elements repository.
        branch: update-from-stoplightio-elements
